tasks:
  - humor
  - sarcasm
seed: 42
json_file_dir: output/rebuild/subtitle
feature_file_dir: output/extract_feature/combine
output_dir: cache/classifier

train_ratio: 0.8
valid_ratio: 0.1
test_ratio: 0.1


skip_season_eps:
#  - "第2季 第2期"
#  - "第2季 第3期"
#  - "第2季 第4期"
#  - "第2季 第5期"
#  - "第2季 第6期"
#  - "第2季 第7期"
#  - "第3季 第2期"
#  - "第4季 第10期"
#  - "第4季 第3期"
#  - "第4季 第4期"
#  - "第4季 第8期"
#  - "第4季 第1期"
#  - "第2季 第10期"
#  - "第2季 第1期"
#  - "第2季 第9期"
#  - "第3季 第10期"
#  - "第3季 第1期"
#  - "第3季 第5期"
#  - "第3季 第6期"
#  - "第3季 第7期"

  - "第2季 第8期"
  - "第4季 第2期"
  - "第3季 第3期"
  - "第3季 第4期"
  - "第3季 第8期"
  - "第3季 第9期"
  - "第4季 第5期"
  - "第4季 第6期"
  - "第4季 第7期"
  - "第4季 第9期"